# Generated by Django 4.2.16 on 2024-09-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("passwords", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="password",
            name="password",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="password",
            name="service_name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
